version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: reniec_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: reniecdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mia123
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
